### ISSUE TITLE
Smooth transition when switching from light to dark mode

### ISSUE THREAD

**Issue by jtsimoes** [vinorodrigues/bootstrap-dark#11]
Hey!

First of all, thank you so much for this. I was looking for dark mode on Bootstrap for ages!

I noticed that switching from light to dark mode (or vice-versa) is a little too "aggressive". I have been playing with the transitions and I think I have found a good trick to smooth this transition and decided to come here and share it with you.

This is really simple and **CSS only**:
```css
body {
    transition: 0.5s;   /* change the duration for whatever you want */
}
```

I've not test on all cases, but I think this works for all methods: when the light and the dark mode are all in the **same CSS file** (for example, on `bootstrap-nightshade.css`) and when the light and the dark mode are in **two separate files** (for example, on `bootstrap-nightfall.css`).

Do you consider this a possible feature or will you leave it up to each user?

**Comment by vinorodrigues** [comment]
This is smart!  Thank you.  Let me digest this with a few experiments of my own.  (I'll leave this open until I do...)

**Comment by ltguide** [comment]
I observed the contents of my test page sliding when a modal opened with that body transition property set. I liked the concept though, so I edited my theme switch button to set that property when it's toggled. In my setup, I dont need to worry about removing the property (to prevent later issues before the page reloads), but it could be removed from a timeout.
