### ISSUE TITLE
Incorrect import paths in npm version?

### ISSUE THREAD

**Issue by picobots** [vinorodrigues/bootstrap-dark#16]
First off, this is a great project. Thanks for all your hard work on this! I'm excited to give it a try.

I'm attempting to include bootstrap-dark-4 in my project via npm (`npm install bootstrap-dark-4`), but when I include bootstrap-dark.scss like this:

`@import "../../../../node_modules/bootstrap-dark-4/scss/bootstrap-dark";`

I get a SASS compilation error because the relative pathing isn't correct in bootstrap-dark.scss:

```
SassError: Can't find stylesheet to import.
   ╷
13 │ @import "../node_modules/bootstrap/scss/functions";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\bootstrap-dark-4\scss\bootstrap-dark.scss 13:9
```

Shouldn't the correct import statements throughout bootstrap-dark.scss be more like `"../../bootstrap/scss/functions"` instead of `"../node_modules/bootstrap/scss/functions"`?

The npm packages for bootstrap and bootstrap-dark-4 sit side-by-side in the node_modules folder, so the `../node_modules/` part of the import path isn't correct, which is what causes the SASS compilation errors. It seems like the npm version of bootstrap-dark-4 is expecting to be placed in a subfolder outside of the node_modules folder, rather than inside of node_modules as it is when it's installed by npm.

Am I missing something? Did I set this up incorrectly?

![bootstrap-dark-4-npm](https://user-images.githubusercontent.com/2413048/170322764-8d8b9878-aa90-49ae-b7ea-b34d2730a88d.png)

**Comment by vinorodrigues** [comment]
`bootstrap-dark.scss` is intended for stand alone compile *(within the project it's hosted in)*
If you intent to use portions of it; then you will need to include the portions you wish with correct paths.

**Comment by picobots** [comment]
Hmm. I'm not sure if I totally follow. I'm attempting to use Method 4 ("Bootstrap-Dark") as outlined in your main readme, where I end up with the following in the HTML:

```
<meta name="color-scheme" content="light dark">
<link rel="stylesheet" href="bootstrap-dark.css">
```

But I want to compile the SASS myself so I can customize some of the Bootstrap variables first. The way to do this with a vanilla Bootstrap setup is like this:

```
@import "_my_custom_bootstrap_variables";
@import "../../../../node_modules/bootstrap/scss/bootstrap";
```

I had thought I was supposed to just replace the second import (Bootstrap's bootstrap.scss) with your bootstrap-dark.scss, like this:

```
@import "_my_custom_bootstrap_variables";
@import "../../../../node_modules/bootstrap-dark-4/scss/bootstrap-dark";
```

So that's not the intended way to build from SASS with Bootstrap Dark? Which Bootstrap Dark file am I supposed to include after defining and importing my custom variables?

**Comment by vinorodrigues** [comment]
general rule of thumb:  in your own project `@import` any file with a `_`, but do not a non-_ file.

If you want your own variables then create a new file that will be compiled and fill it with the includes... basically make a copy of the `bootstrap-dard.scss` file, but with the correct paths to the two libraries.
