### ISSUE TITLE
How to locally build bootstrap-unlit?

### ISSUE THREAD

**Issue by crazyfx1** [vinorodrigues/bootstrap-dark#6]
I want to use the bootstrap-unlit Method 4b with custom colors. 
How can I build it? 
There is no gulp-task and if I change the sassSrc2 to unlit, I get an error because some files like variables-save-alt do not exist.

**Comment by vinorodrigues** [comment]
Oh.  Darn.  My fault.   I'd did a `_*` in my gitignore file and they were never committed.  Thanks for the spot - fixed now.

**Comment by crazyfx1** [comment]
It works, thanks. Good work on the project ;)
